---
- name: Install dependencies for Ubuntu
  apt:
    pkg:
        - build-essential
        - gcc
        - git
        - libcurl4-openssl-dev
        - libffi-dev
        - libreadline-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - make
        - zlib1g-dev
    state: present
    force: yes
    update_cache: yes
    cache_valid_time: 3600

  become: true
