---
- name: Install dependencies for Centos
  yum:
    pkg:
      - git
      - zlib
      - zlib-devel
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - libyaml-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - curl
      - sqlite-devel
    state: present
    update_cache: yes

  become: true
